added many logs fixed basic android rendering, still lots of work to do but we're on the right path now!

diff --git a/android/NativeTest/build b/android/NativeTest/build
--- a/android/NativeTest/build
+++ b/android/NativeTest/build
@@ -1,8 +1,18 @@
+function testbuild {
+    "$@"
+    local status=$?
+    if [ $status -ne 0 ]; then
+        echo "error with $1"
+        exit 1
+    fi
+    return $status
+}
+
 export NDK_MODULE_PATH=$(pwd)/../../
 echo ----------------------------------------------------------------------------------------
 echo Build lib
 echo ----------------------------------------------------------------------------------------
-ndk-build -j 8 NDK_DEBUG=1
+testbuild ndk-build -j 8 NDK_DEBUG=1
 
 
 echo ----------------------------------------------------------------------------------------
